### ISSUE TITLE
deploy projects to maven central

### ISSUE THREAD

**Issue by AllesEins** [JULIELab/jcore-projects#2]
- [x] jcore-biosem-ae-bionlp-st11
- [x] jcore-jnet-ae-biomedical-english
- [x] jcore-jpos-ae-medical-german
- [x] jcore-jsbd-ae-biomedical-english
- [x] jcore-jtbd-ae-biomedical-english
- [x] jcore-lingpipegazetteer-ae-dummy-implementation
- [x] jcore-medline-reader
- [x] jcore-mstparser-ae-biomedical-english
- [x] jcore-opennlp-chunk-ae-genia
- [x] jcore-opennlp-postag-ae-pennbioie
- [x] jcore-opennlp-sentence-ae-genia-pennbio-english
- [x] jcore-opennlp-token-ae-biomedical-english
- [x] jcore-pubmed-reader

**Comment by AllesEins** [comment]
* `jcore-biosem-ae-bionlp-st11 & jcore-medline-reader` need their updated dependencies.
* `jcore-pubmed-reader` needs its test fixed
* `jcore-mstparser-ae-biomedical-english` needs the updated mst-parser

**Comment by AllesEins** [comment]
pubmed-reader tests work with xml-mapper 2.0.0 but not with xml-mapper 2.0.1

**Comment by khituras** [comment]
For me, the `pubmed-reader` tests are working `with xml-reader` 2.0.0 and  2.0.1. Don't know what's wrong

**Comment by AllesEins** [comment]
resolved issue: `xml-reader` had `jcore-types` 2.0.0 dependency and it seems the newer `jcore-types` 2.0.1 dependency from `xml-mapper` did not 'win'

*note*: do we need to declare the `jcore-types` dependency in the `pubmed`- & `medline-reader`, as well; seems to be redundant?

**Comment by khituras** [comment]
No, we don't. In `pubmed-reader` there is no direct dependency to `jcore-types` actually. So it can be removed from the `medline-reader` as well.

**Comment by AllesEins** [comment]
hm, so maybe I put the dependency there...

closed
