### ISSUE TITLE
Write descriptor locations into pom.xml

### ISSUE THREAD

**Issue by khituras** [JULIELab/jcore-projects#8]
We could write the descriptor locations into the project's pom.xml files. These are rather easily opened from eclipse by clicking on the dependency in the "Dependency Hierarchy" view. This would prevent the need to go to GitHub just to look up the descriptor location.

**Comment by fmatthies** [comment]
And you would put them under `description` in the pom?
Or we could hijack the `url` section...

**Comment by khituras** [comment]
At the moment, it rather seems we have settled with putting the descriptor location into the GitHub README. At least we do it consistently in JCoRe base. I think for the moment we will just stick with that.
